name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - run: bazel build -c opt //cmd
      - run: |
          mkdir -p dist
          ln -s bazel-bin/cmd/cmd_/cmd dist/bazeldnf-linux-x86_64
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./dist/bazeldnf-linux-x86_64